version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - .:/nursing-request # ソースコード変更したらDocker側も即反映されるように
      - /app/log
    environment:
      - RAILS_ENV=production

  nginx:
    build: containers/nginx
    ports:
      - "80:80"
    volumes_from:
      - web
    depends_on:
      - web