version: '3'
services:
  db:
    image: postgres:12.4
    environment:
      POSTGRES_USER:  <%= Rails.application.credentials.rds[:username] %>
      POSTGRES_PASSWORD: <%= Rails.application.credentials.rds[:password] %>
    #ports:
      #- '5432:5432' # ホストからゲストへポートフォワード
    #volumes:
      #- postgresql-data:/var/lib/postgresql/data
    
  web:
    build:
      context: .
      dockerfile: Dockerfile
    #command: bundle exec rails s -p 3000 -b '0.0.0.0'
    tty: true
    stdin_open: true
    depends_on:
      - db # DB側のコンテナが出来上がってからwebを実行する
    #ports:
      #- "3000:3000" # ホストからゲストへポートフォワード
    links:
      - db  #railsが同じネットワークに属する
    volumes:
      - .:/nursing-request # ソースコード変更したらDocker側も即反映されるように
      - /app/log
    environment:
      - RAILS_ENV=production

  nginx:
    build: containers/nginx
    ports:
      - "80:80"
    volumes_from:
      - web
    depends_on:
      - web

#volumes:
  #postgresql-data:
    #driver: local